name: GitHub Action Test
run-name: GitHub Action Test
on: 
  pull_request:
    types: opened
    
jobs:
  Test-Job:
    runs-on: ubuntu-latest
    
    permissions:
      pull-requests: read
      
    steps:  
      - name: Test Step
        run: echo "🎉 The job was triggered by a ${{ github.actor }}." 
